# Generated by Django 6.1.1 on 2026-10-07 03:52

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('teacher_code', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=70)),
                ('subject', models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('ICT', 'ICT'), ('Social Science', 'Social Science'), ('Political Science', 'Political Science'), ('History', 'History'), ('Others', 'Others')])),
                ('address', models.CharField(max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BD')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher/')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teacher',
            },
        ),
    ]
