# Generated by Django 6.1.1 on 2026-10-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('ICT', 'ICT'), ('Social Science', 'Social Science'), ('Political Science', 'Political Science'), ('History', 'History'), ('Others', 'Others')]),
        ),
    ]
