# Generated by Django 6.1.1 on 2026-10-04 11:17

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('father_name', models.CharField(max_length=70)),
                ('mother_name', models.CharField(max_length=70)),
                ('roll', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student/')),
                ('gardian_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BD')),
            ],
        ),
    ]
