# Generated by Django 6.1.1 on 2026-10-07 03:52

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=[('mid', 'Mid'), ('final', 'Final')], max_length=6)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('subject_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('father_name', models.CharField(max_length=70)),
                ('mother_name', models.CharField(max_length=70)),
                ('roll', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student/')),
                ('gardian_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BD')),
                ('address', models.CharField(max_length=150)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'student',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('GPA', models.CharField(max_length=3)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='student_info.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='student_info.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='student_info.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'exam', 'subject'), name='unique_student_exam_subject')],
            },
        ),
    ]
