# Generated by Django 6.1.1 on 2026-10-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0002_exam_subject_alter_student_options_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
