# Generated by Django 6.1.1 on 2026-09-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_notice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
